"""TokenDye SFT training skeleton (Qwen3.5-4B).

Baseline objective:

    L = CE(response) + w_anchor * ||h_dyed - h_base||^2 (prompt tokens)
        + wd * ||delta||^2                  (optimizer weight decay)

Data format (JSONL, one sample per line):

    {"segments": [{"role": "system|user|assistant|tool", "content": "..."}], "response": "..."}

`segments` hold the context (multi-turn supported); `response` is the only
supervised target. CoT is not part of the training data: it is generated by
the model during rollout, and only the post-`</think>` output is judged.

Usage:
    QWEN_MODEL_PATH=/path/to/Qwen3.5-4B uv run python \\
        example/Qwen3.5/train.py --data train.jsonl --steps 200
    QWEN_MODEL_PATH=/path/to/Qwen3.5-4B uv run python \\
        example/Qwen3.5/train.py --data train.jsonl --smoke --steps 3
"""

from __future__ import annotations

import argparse
import json
import os
import random
import sys
import time
from datetime import datetime, timezone
from pathlib import Path

import torch
from loguru import logger
from torch.nn import functional as F

sys.path.insert(0, str(Path(__file__).resolve().parents[1] / "src"))

from config import DEFAULT_MODEL_PATH, LABELS, RESPONSE_ID

from tokendye import Dye, install_dye
from tokendye.hf import ensure_python_headers, load_model
from tokendye.training import collate, masked_cross_entropy, tokenize_chat


def tokenize_sample(tokenizer, sample: dict, max_seq_len: int) -> tuple[list[int], list[int]]:
    """Render one sample into token ids and per-token role labels."""
    messages = []
    spans = []
    for seg in sample.get("segments") or []:
        role = seg.get("role", "")
        content = seg.get("content", "")
        if not content:
            continue
        if role in ("system", "user"):
            messages.append({"role": role, "content": content})
            spans.append((LABELS.index(role), content))
        else:
            # assistant 历史轮次 / tool 等上下文：渲染为消息，不染色
            messages.append({"role": role, "content": content})
    response = sample.get("response")
    if response:
        messages.append({"role": "assistant", "content": response})
        spans.append((LABELS.index("response"), response))
    return tokenize_chat(tokenizer, messages, spans, max_seq_len, add_generation_prompt=False)


def load_samples(data_path: Path | None) -> list[dict]:
    if data_path is None:
        raise SystemExit("请提供外部训练数据：--data train.jsonl")
    with data_path.open(encoding="utf-8") as f:
        return [json.loads(line) for line in f if line.strip()]


def validate_samples(samples: list[dict]) -> None:
    """SFT 数据必须包含 segments 列表和 response；role 必须合法。"""
    known_roles = {"system", "user", "assistant", "tool"}
    for i, sample in enumerate(samples, 1):
        segments = sample.get("segments")
        if not isinstance(segments, list) or not segments:
            raise SystemExit(f"样本 {i} 缺少 segments 列表")
        for j, seg in enumerate(segments, 1):
            if not isinstance(seg, dict) or not seg.get("content"):
                raise SystemExit(f"样本 {i} 的 segments[{j}] 缺少 content")
            if seg.get("role") not in known_roles:
                raise SystemExit(
                    f"样本 {i} 的 segments[{j}] role 非法：{seg.get('role')!r}"
                    f"（应为 {sorted(known_roles)}）"
                )
        if not sample.get("response"):
            raise SystemExit(
                f"样本 {i} 缺少 response（最终监督正文）"
                f"（attacks.jsonl 是 DAPO 攻击集，不能用于 SFT）"
            )


def label_cosine_similarity(dye: Dye) -> torch.Tensor:
    """Cosine similarity between role delta vectors (mean over layers)."""
    flat = dye.delta.mean(dim=1)  # (num_labels, d_model)
    flat = F.normalize(flat, dim=-1)
    return flat @ flat.T


def main() -> None:
    ensure_python_headers()
    parser = argparse.ArgumentParser(
        description="TokenDye SFT 训练骨架（逐层染色）",
    )
    parser.add_argument(
        "--model-path",
        default=os.environ.get("QWEN_MODEL_PATH", DEFAULT_MODEL_PATH),
        help="模型路径（也可用环境变量 QWEN_MODEL_PATH 传入）",
    )
    parser.add_argument("--data", type=Path, default=None, help="JSONL 训练数据")
    parser.add_argument("--smoke", action="store_true", help="使用外部数据执行冒烟测试")
    parser.add_argument("--steps", type=int, default=100)
    parser.add_argument("--batch-size", type=int, default=2)
    parser.add_argument("--max-seq-len", type=int, default=512)
    parser.add_argument("--lr", type=float, default=1e-2)
    parser.add_argument("--weight-decay", type=float, default=1e-3)
    parser.add_argument("--w-anchor", type=float, default=0.1)
    parser.add_argument("--clip", type=float, default=1.0)
    parser.add_argument("--log-every", type=int, default=10)
    parser.add_argument("--save-every", type=int, default=0)
    parser.add_argument(
        "--output-dir",
        type=Path,
        default=Path("example/Qwen3.5/.outputs"),
        help="输出根目录，每次运行自动创建时间戳子目录",
    )
    parser.add_argument("--seed", type=int, default=0)
    args = parser.parse_args()

    if not Path(args.model_path).exists():
        raise SystemExit(f"模型目录不存在：{args.model_path}\n请设置 QWEN_MODEL_PATH")
    # Fail fast on bad --data/--smoke before paying the model-loading cost.
    samples = load_samples(args.data)
    validate_samples(samples)

    run_dir = args.output_dir / datetime.now(tz=timezone.utc).astimezone().strftime("%Y%m%d_%H%M%S")
    run_dir.mkdir(parents=True, exist_ok=True)
    logger.remove()
    logger.add(sys.stderr, format="{time:HH:mm:ss} | {message}", colorize=False)
    logger.add(
        run_dir / "train.log",
        format="{time:YYYY-MM-DD HH:mm:ss.SSS} | {message}",
        encoding="utf-8",
    )
    logger.info("{}", f"output dir: {run_dir}")

    torch.manual_seed(args.seed)
    random.seed(args.seed)
    device = "cuda" if torch.cuda.is_available() else "cpu"
    logger.info("{}", f"device: {device}")

    from transformers import AutoTokenizer

    tokenizer = AutoTokenizer.from_pretrained(args.model_path)
    if tokenizer.pad_token_id is None:
        tokenizer.pad_token_id = tokenizer.eos_token_id

    model = load_model(args.model_path, device)
    model.requires_grad_(False)
    if device == "cuda":
        torch.cuda.reset_peak_memory_stats()

    text_cfg = getattr(model.config, "text_config", model.config)
    dye = Dye(LABELS, text_cfg.num_hidden_layers, text_cfg.hidden_size).to(model.device)
    controller = install_dye(model, dye)
    logger.info("{}", f"dye params: {dye.num_parameters:,}")

    # Capture the last-layer hidden states (dyed and base) for the anchor term.
    captured: dict[str, torch.Tensor] = {}

    def capture_hook(module, args, output):
        captured["h"] = output[0] if isinstance(output, (tuple, list)) else output

    controller.layers[-1].register_forward_hook(capture_hook)

    logger.info("{}", f"samples: {len(samples)}")

    batches = []
    pad_id = tokenizer.pad_token_id or tokenizer.eos_token_id
    for start in range(0, len(samples), args.batch_size):
        chunk = samples[start : start + args.batch_size]
        tokenized = [tokenize_sample(tokenizer, s, args.max_seq_len) for s in chunk]
        batches.append(collate(tokenized, pad_id, args.max_seq_len, model.device))
    if not batches:
        raise SystemExit("no usable training samples")
    total_response = sum(int((batch["dye_mask"] == RESPONSE_ID).sum()) for batch in batches)
    if total_response == 0:
        raise SystemExit("训练数据里没有 response 段，无法计算行为损失；请检查数据格式")

    optimizer = torch.optim.AdamW(dye.parameters(), lr=args.lr, weight_decay=args.weight_decay)

    step = 0
    t0 = time.time()
    while step < args.steps:
        for batch in batches:
            step += 1
            if step > args.steps:
                break

            # Dyed forward: logits + last-layer hidden states.
            controller.set_labels(batch["dye_mask"])
            out = model(input_ids=batch["input_ids"], attention_mask=batch["attention_mask"])
            logits = out.logits
            dyed_h = captured["h"]

            ce_response = masked_cross_entropy(
                logits, batch["input_ids"], batch["dye_mask"] == RESPONSE_ID
            )
            # Frozen-base forward (no grad): anchor hidden states + logits for metrics.
            controller.clear_labels()
            with torch.no_grad():
                base_out = model(
                    input_ids=batch["input_ids"],
                    attention_mask=batch["attention_mask"],
                )
                base_h = captured["h"]
                base_logits = base_out.logits

            anchor_mask = (batch["dye_mask"] < 2) & batch["attention_mask"].bool()
            if anchor_mask.any():
                anchor = F.mse_loss(dyed_h[anchor_mask].float(), base_h[anchor_mask].float())
            else:
                anchor = torch.zeros((), device=model.device)

            loss = ce_response + args.w_anchor * anchor

            optimizer.zero_grad()
            loss.backward()
            torch.nn.utils.clip_grad_norm_(dye.parameters(), args.clip)
            optimizer.step()
            dye.delta.data.clamp_(-0.5, 0.5)  # scale in [0.5, 1.5]

            if step == 1 or step % args.log_every == 0:
                grad_norm = sum(
                    p.grad.norm().item() for p in dye.parameters() if p.grad is not None
                )
                vram = torch.cuda.max_memory_allocated() / 1e9 if device == "cuda" else 0.0
                decay_diff = "n/a"
                if anchor_mask.any():
                    diff = (logits - base_logits).abs().max(dim=-1).values[anchor_mask]
                    decay_diff = f"{diff.mean().item():.3e}"
                logger.info(
                    "{}",
                    f"step {step}/{args.steps} loss={loss.item():.4f} "
                    f"ce_resp={ce_response.item():.4f} "
                    f"anchor={anchor.item():.3e} |delta|={dye.delta.abs().mean().item():.4f} "
                    f"grad={grad_norm:.3f} vram={vram:.2f}GB decay_diff={decay_diff}",
                )
                sim = label_cosine_similarity(dye)
                logger.info("{}", "    role delta cosine sim:")
                for i in range(sim.size(0)):
                    logger.info(
                        "{}", "      " + " ".join(f"{sim[i, j]:.3f}" for j in range(sim.size(0)))
                    )

            if args.save_every and step % args.save_every == 0:
                save_path = run_dir / f"dye_step{step}.pt"
                torch.save(dye.state_dict(), save_path)
                logger.info("{}", f"    saved {save_path}")

    final_path = run_dir / "dye_final.pt"
    torch.save(dye.state_dict(), final_path)
    peak_vram = torch.cuda.max_memory_allocated() / 1e9 if device == "cuda" else 0.0
    logger.info(
        "{}", f"done in {time.time() - t0:.1f}s; peak_vram={peak_vram:.2f}GB; saved {final_path}"
    )
    controller.remove()


if __name__ == "__main__":
    main()
